vehicle_controller:
  ros__parameters:
    wheel_data:
      wheels_name:
        - lf_wheel
        - rf_wheel
        - rr_wheel
        - lr_wheel
      lf_wheel:
        motors_id: [1, 2]
        joints:
          - "lf_swerve_joint"
          - "lf_wheel_joint"
        pos_on_vehicle: [0.24858, 0.17929]
        wheel_radius: 0.075
      rf_wheel:
        motors_id: [3, 4]
        joints:
          - "rf_swerve_joint"
          - "rf_wheel_joint"
        pos_on_vehicle: [0.24858, -0.18071]
        wheel_radius: 0.075
      rr_wheel:
        motors_id: [5, 6]
        joints:
          - "rr_swerve_joint"
          - "rr_wheel_joint"
        pos_on_vehicle: [-0.28642, -0.18071]
        wheel_radius: 0.075
      lr_wheel:
        motors_id: [7, 8]
        joints:
          - "lr_swerve_joint"
          - "lr_wheel_joint"
        pos_on_vehicle: [-0.28642, 0.17929]
        wheel_radius: 0.075

    dir_acc_max: 1.0
    ang_acc_max: 1.0